### PR TITLE
Testing for the closeScope0 function

### PR DESCRIPTION
**Pull request by EricYangIBM**
Java command:
`build/linux-x86_64-server-release/images/jdk/bin/java
    --add-opens jdk.incubator.foreign/jdk.internal.foreign=ALL-UNNAMED
    --add-opens java.base/jdk.internal.misc=ALL-UNNAMED
    --add-modules jdk.incubator.foreign Test.java`

Signed-off-by: Eric Yang <eric.yang@ibm.com>

### CODE REVIEW

**Comment by EricYangIBM** [comment]
Sample output:
```
root@purpurin1:~/openj9-openjdk-jdk16# build/linux-x86_64-server-release/images/jdk/bin/java --add-opens jdk.incubator.foreign/jdk.internal.foreign=ALL-UNNAMED --add-opens java.base/jdk.internal.misc=ALL-UNNAMED --add-modules jdk.incubator.foreign Test.java
WARNING: Using incubator modules: jdk.incubator.foreign
warning: using incubating module(s): jdk.incubator.foreign
Note: Test.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 warning
gabob
gabob
gabob
Method: wait
Method: remove
Method: remove
Method: run
Method: run
Method: waitForNotification
Method: run
Method: getAndBitwiseOrByte
Method: getAndBitwiseOrByte
Method: getAndBitwiseOrByteInternal
Scoped Annotation
Slot class: jdk/internal/foreign/MemoryScope$SharedScope@
Found
java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
        at Test$2.run(Test.java:46)
Caused by: java.lang.IllegalStateException: Cannot close while another thread is accessing the segment
        at jdk.incubator.foreign/jdk.internal.foreign.MemoryScope$SharedScope.justClose(MemoryScope.java:282)
        at jdk.incubator.foreign/jdk.internal.foreign.MemoryScope.close(MemoryScope.java:97)
        ... 5 more
```

**Comment by tajila** [comment]
you'll need to add the test to `/openj9/test/functional/Java16andUp`

**Comment by EricYangIBM** [comment]
@tajila The test I wrote is kinda bad. It consistently throws the correct exception on my machine but I don't think it would be consistent across other machines. Also I modified the Unsafe class to wait for the closer thread. I'm not sure how else I would test this function though.
Does adding the test to `/openj9/test/functional/Java16andUp` run the test with every functional test run? If so it may erroneously fail

**Comment by tajila** [comment]
@EricYangIBM  can you add your testing changes to this PR

**Comment by tajila** [comment]
also please rebase

**Pull request closed without merging**
